---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media:
    - Jellyfin:
        href: http://jellyfin.morton.lan
        description: Watch movies and shows
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"
          enableBlocks: true
          enableNowPlaying: false
    - Seerr:
        href: http://seerr.morton.lan
        description: Request movies and TV
        widget:
          type: seerr
          url: http://seerr:5055
          key: "{{HOMEPAGE_VAR_SEERR_KEY}}"
    - Prowlarr:
        href: http://prowlarr.morton.lan
        description: Indexers
    - qBittorrent:
        href: http://qbit.morton.lan
        description: Downloads
    - SABnzbd:
        href: http://sabnzbd.morton.lan
        description: Newsgroups
    - Navidrome:
        href: http://navidrome.morton.lan
        description: Music streaming
    - Tdarr:
        href: http://tdarr.morton.lan
        description: Automated media transcoding
        widget:
          type: tdarr
          url: http://tdarr:8265

- Apps:
  - Glance:
      href: http://glance.morton.lan
      description: Dashboard
  - FreshRSS:
      href: http://freshrss.morton.lan
      description: RSS feed reader
  - RomM:
      href: http://romm.morton.lan
      description: Game library manager
  - Wiki:
      href: http://wiki.morton.lan:8084
      description: Offline Wikipedia and reference
  - WeatherBug:
      href: https://www.weatherbug.com/weather-forecast/hourly/fayetteville-ar-72701?tu=1&pu=1&wsu=1
      description: Weather Forecast

- Utilities:
  - Grafana:
      href: https://malcyon.grafana.net
      description: Metrics and logs
  - Nginx Proxy Manager:
      href: http://npm.morton.lan
      description: Reverse proxy
  - Pi-hole:
      href: http://pihole.morton.lan/admin/
      description: DNS and ad blocking

- Downloads:
    - Radarr:
        href: http://radarr.morton.lan
        description: Movies management
        widget:
          type: radarr
          url: http://radarr:7878
          key: "{{HOMEPAGE_VAR_RADARR_KEY}}"
          enableQueue: true
    - Sonarr:
        href: http://sonarr.morton.lan
        description: TV management
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
          enableQueue: true
